'use client'
import '../style/globals.scss'
type Props = {
  children: React.ReactNode
}
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}
import { useEffect, useState } from 'react'

export default function RootLayout({ children }: Props) {
  const [loading, setLoading] = useState(false)
  useEffect(() => {
    setLoading(true)
  }, [])
  return (
    <html lang='en'>
      <head {...metadata} />
      <body className={inter.className}>
        <main className={loading ? '' : 'hidden'}>{children}</main>
      </body>
    </html>
  )
}
