'use client'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

import { Layout } from 'antd'
import { useEffect, useState } from 'react'

import Header from '../../components/common/header'
import Footer from '../../components/common/footer'
const { Content } = Layout

export const metadata = {
  title: 'NextJS - Hiep',
  description: 'Generated by create next app',
}

type Props = {
  children: React.ReactNode
}
export default function RootLayout({ children }: Props) {
  const [loading, setLoading] = useState(false)
  useEffect(() => {
    setLoading(true)
  }, [])
  return (
    <html lang='en'>
      <head {...metadata} />
      <body className={inter.className}>
        <main className={loading ? '' : 'hidden'}>
          <Layout>
            <Header />
            <Layout hasSider className='my-1'>
              <Content className='container'>
                <div>{children}</div>
              </Content>
            </Layout>
            <Footer />
          </Layout>
        </main>
      </body>
    </html>
  )
}
